version: "3"
services:
  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
      - db.env
    environment:
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_CONFIG_URL=https://raw.githubusercontent.com/SSharshunov/openwrt_helper/master/master.cfg
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://friends.usrsrc.ru:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
    links:
      - db
    depends_on:
      - db
    ports:
      - "8010:8010"
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    expose:
      - 5432

  worker:
    #build: https://raw.githubusercontent.com/SSharshunov/openwrt_helper/master/worker/Dockerfile
    build: "./worker"
    # image: "buildbot/buildbot-worker:master"
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: hisi-openwrt-worker
      WORKERPASS: pass
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    volumes:
      - /home/$USER/buildbot:/buildbot
      - /home/$USER/sources:/sources
      - /home/$USER/config.ini:/buildbot/config.ini
      - /home/$USER/.gitconfig:/home/buildbot/.gitconfig
    links:
      - buildbot
